### PR TITLE
replaced poa and vor counts in article history with versions list

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
The `dist/` folder is now regenerated by Alfred upon merging into `develop` (it performs an additional commit); so we introduced this check https://github.com/elifesciences/api-raml/pull/41 that says that no `dist/` file should be modified in PR as they would be overwritten anyway. You should rebase this removing the modification to `dist/` I think.

**Comment by lsh-0** [comment]
the .gitignore should be ignoring `dist/` then and this caveat should be noted in the readme. you can ignore a directory but still commit changes with `--force`.

**Comment by giorgiosironi** [comment]
Nice idea, I'll put it into the `Jenkinsfile`.

**Comment by thewilkybarkid** [comment]
@lsh-0 `dist` can't be ignored as we need to be able to load the compiled files in other projects. The reason for disallowing manual changes to it is to avoid merge conflicts.

**Comment by thewilkybarkid** [comment]
The alternative is to have a separate repo that's the compiled version, but this was considered simpler.

**Comment by lsh-0** [comment]
It's fine, so long as these exceptions to the rule are documented and the hapless developer (me) is prevented from shooting himself in the foot. I'll update the `readme` and revert my changes to `dist`.

**Comment by lsh-0** [comment]
I'll fix up the lint issue before merging

```
$ time ./bldr "cmd:journal--end2end,sleep 20"
1475059371.710787 - WARNING - MainProcess - buildercore.decorators - TODO: embarassing code. some of these constants should be pulled form project config or given better names.
1475059371.711882 - INFO - MainProcess - buildercore.config - using settings path u'/home/luke/dev/python/builder/settings.yml'
Connecting to: journal--end2end
connecting to a journal instance in region us-east-1
connecting to a journal instance in region us-east-1
1475059375.090180 - INFO - MainProcess - buildercore.core - Executing <function <lambda> at 0x7fe016300500> on all ec2 nodes ([u'54.227.6.72', u'52.91.22.168'])
[54.227.6.72] Executing task '<lambda>'
[52.91.22.168] Executing task '<lambda>'
[52.91.22.168] run: sleep 20
[54.227.6.72] run: sleep 20
1475059375.316577 - INFO - 54.227.6.72 - paramiko.transport - Connected (version 2.0, client OpenSSH_6.6.1p1)
1475059375.317266 - INFO - 52.91.22.168 - paramiko.transport - Connected (version 2.0, client OpenSSH_6.6.1p1)
1475059375.872038 - INFO - 52.91.22.168 - paramiko.transport - Authentication (publickey) successful!
1475059375.875191 - INFO - 54.227.6.72 - paramiko.transport - Authentication (publickey) successful!

Done.

real    0m24.849s
user    0m2.537s
sys 0m0.170s
```

**Comment by giorgiosironi** [comment]
I think the last comment is for another PR

**Comment by lsh-0** [comment]
ha, you're right. multitasking ftw

**Comment by giorgiosironi** [comment]
@thewilkybarkid ignoring does not work even with `--force`? If the other projects load this through Composer they shouldn't they still get everything committed with `--force`?

**Comment by lsh-0** [comment]
erm - so, what I was getting at was, keeping `./dist` in there, but only having one process (Alfred) doing the compiling and `--force` commit of the changes. All projects would continue to have access to the compiled version as per usual and developers wouldn't be able to commit changes to `./dist` without being explicit (tacking a `--force` to their commit)

clear as mud?

**Comment by thewilkybarkid** [comment]
Ah, gotcha. Sounds like it would work.

**Comment by giorgiosironi** [comment]
Implemented in https://github.com/elifesciences/api-raml/pull/71

**Comment by lsh-0** [comment]
thanks, @giorgiosironi

**Pull request merged**
