### PR TITLE
Adding sample of captionless image

### PR DESCRIPTION
**Pull request by giorgiosironi**
See also https://github.com/elifesciences/journal/pull/409

### CODE REVIEW

**Comment by NuclearRedeye** [comment]
@lsh-0 update and merge or close?

**Comment by lsh-0** [comment]
api-raml changes should be strictly documented, they affect many applications.

I don't know what prompted this change but it would be good to pin down it's origin before closing.

**Comment by lsh-0** [comment]
Might be related to this change by @nlisgo : https://github.com/elifesciences/patterns-php/blob/503ff586e2abf7f7524d881adaf64c82f4e2ff3a/tests/src/ViewModel/CaptionedAssetTest.php

**Comment by NuclearRedeye** [comment]
@nlisgo Can you shed any light on this PR?

**Comment by nlisgo** [comment]
> @nlisgo Can you shed any light on this PR?

This can be merged in. No schema change here. This just verifies that an image with a caption is valid.

**Comment by lsh-0** [comment]
@nlisgo , if this is still good to merge and doesn't interfere with the social images work, could you merge it please? I think it should be safe.

**Comment by nlisgo** [comment]
@lsh-0 can you confirm you are happy for this to be a minor version bump?

**Comment by NuclearRedeye** [comment]
> @lsh-0 can you confirm you are happy for this to be a minor version bump?

@nlisgo As this seems to only be adding an example rather that changing the API do we need to bother bumping the version number? I'm not the maintainer, but my 2 cents would be that the version only needs to apply to the API and hence in this case it should be fine to leave it as is.

**Comment by lsh-0** [comment]
yeah, another example of not needing a version bump.

**Pull request merged**
