### PR TITLE
ELPP-1850 Add figures PDF

### PR DESCRIPTION
**Pull request by thewilkybarkid**
cc @gnott @lsh-0

### CODE REVIEW

**Comment by gnott** [comment]
I think this might be somewhere in lax and not in the bot-lax-adaptor, so probably over to @lsh-0 for more guidance of the next steps.

**Comment by lsh-0** [comment]
um - so without much context, is this about the CDN? if so, then yes - ticket is assigned to me. I'll take a look at what is left to do today

**Comment by giorgiosironi** [comment]
Should still be in bot-lax-adaptor as it's part of the JSON (fragments) being generated there?

**Comment by gnott** [comment]
I guess to be more accurate I meant the data is not in the XML, so it doesn't apply to the "first level" of scraping which only looks at the XML (which is the only one I'm directly involved in right now).

**Pull request merged**
