### PR TITLE
Architecture Decision Records

### PR DESCRIPTION
**Pull request by giorgiosironi**
Since it's not the first time we need to document an architecture decision, and we need a lightweight, easy to update system for this task.

This has been created with https://github.com/npryce/adr-tools but it's just a folder with text files.

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
We shouldn't have `0001` here. It should be at a team/company-wide level.

**Comment by giorgiosironi** [comment]
It's not very important, more demonstrative, will remove&renumber.

**Comment by thewilkybarkid** [comment]
@giorgiosironi Don't seem to be able to SSH in to fix the build

**Comment by giorgiosironi** [comment]
It's possible the daily updates (that should propagate SSH keys) are not running because of the server going up and down.

**Comment by giorgiosironi** [comment]
You should be able to, since a long time:
```
elife@ci--libraries:~$ cat .ssh/authorized_keys | tail -n 1
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC4z8qiqGpf4UrqLWwalQNokQsRW4Ndz+6DmiHd2esDYVgKGM7MA1s3ruYhJjfdsqIr37RowdutmyGQkscmpVAEouvadw/1so6mDX6wRb8KP3RGSi2Bgmdoh7UZX41udl43hf4dm8esxpCfSbdd0ybk2lKKerdBWlDSuR2KkjLjSoUR8TPw8vLM13sA7Ig8VIe1lq6q7JXFL1Bg9+09Ozk+UxFivoa+bX+uJlLzgdXfqUgLpJa50n/8twlOWEwopKad8O660m3lf2SYi0ky3Y6ecTIMCxxLHxbk3zaUJm3n2dvtR+PbQI9G3RV/0cyiMoPFbZap7dVbBX84ITrNm1GqdhERPbLi7bduqa5wLkdX7dHh5e8THeulmujZLhQRQgyYGVIeRA98NNcOfSRifDdOFaAQcVEpDgxz1o3Ug91LNwu0DepDoP+RD/v+ViGKVUF6W+tL8PLxL1fe2wtTVt4ad0k+5CwKaQmBPmOr8dOsEiYFg4e2SfVYtjo2oNn00V/f6LHLv5fyl+VMBHcm6D84ITax237tUg8AZzeWEB9YzYxXAiRWpRX9oWKFMMxEH+CekiHbX8X93d4tBbdfev3UzMBlZjhRZ4+stSmFjpqv2Mis45USszIny7k3csKreNWFYtV1kflwtPY5BcCbsHWzk/AXWcs1r0G1mIN27BdiJw== chris
elife@ci--libraries:~$ ls -l .ssh/authorized_keys
-rw------- 1 elife elife 1897 May 10 09:05 .ssh/authorized_keys
```
What does `ssh elife@34.229.204.236` do? The server was turned off, but `./bldr ssh:elife-libraries--ci` turned it on for me.

**Comment by giorgiosironi** [comment]
Ready to merge?

**Comment by thewilkybarkid** [comment]
Yep, just needed builds fixing.

**Pull request merged**
