### PR TITLE
duplicate "application/vnd.elife.article-history+json; version=1" examples in "version=2"

### PR DESCRIPTION
**Pull request by nlisgo**
Also mark version 1 as deprecated.

Have add a changelog entry

### CODE REVIEW

**Comment by lsh-0** [comment]
Should probably be ~`2.3.1`~ `2.2.1`, we're 'patching' something I should have added in ~`2.3.0`~ `2.2.0`. semver doesn't directly apply to non-code so I'm still going by gut instinct here. It's still a good thing to do I think even if we quibble over what constitutes a major/minor/patch version.

I updated this value last time as well: https://github.com/elifesciences/api-raml/blob/develop/dist/api.raml#L5

**Comment by lsh-0** [comment]
edit: 

> Should probably be `2.3.1`

I meant, `2.2.1`

**Comment by nlisgo** [comment]
> I meant, `2.2.1`

If only for adding the samples I would agree but marking the previous media type version as deprecated felt like more of a minor change. But, I'm happy to change to `2.2.1` as suggested. Will add a commit.

**Comment by nlisgo** [comment]
@lsh-0 please approve or add additional feedback. I believe this is ready to roll.

**Review by lsh-0 — APPROVED** [review]

**Pull request merged**
