### PR TITLE
Add optional sentForReview date to article history

### PR DESCRIPTION
**Pull request by nlisgo**
@fred-atherden this is what we discussed yesterday. If you could update this PR with direction of where to find the value in the XML.

I'm not precious about what we call the field name but unless a better name surfaces let's run with this one.#

cc @lsh-0 @gnott @smoqadam

### CODE REVIEW

**Review by fred-atherden — APPROVED** [review]

**Comment by fred-atherden** [comment]
Thanks @nlisgo, In the XML the sent for review date can be found in the same place where accepted and received dates are in non-PRC content. Here it is in the kitchen sink:
https://github.com/elifesciences/XML-mapping/blob/f2dea9d0d0dd620219722aa31fa74189ea4079e2/elife-1234567890-v2/elife-1234567890-v2.xml#L189-L195

**Review by gnott — APPROVED** [review]
Looks simple enough and name is good.

**Comment by nlisgo** [comment]
@fred-atherden can you confirm that there will only ever be one value for this? In the instance that a manuscript is a revised preprint could there possibly be multiple dates here?

**Comment by fred-atherden** [comment]
@nlisgo, yeah - as far as I know we are only planning on showing one sent for review date. This date under PRC will be sort of equivalent to the accepted date under old model papers, which is why we don't intend to show later review dates in the timeline.

**Review by lsh-0 — APPROVED** [review]
Looks fine.

Can I get a link to the issue tracking this work?

**Comment by gnott** [comment]
This is a related issue I think https://github.com/elifesciences/issues/issues/8172, except it may need updating or to be closed in favour of a more recent comprehensive epic issue.

**Comment by nlisgo** [comment]
Thanks for the approval. I will create the epic today and you can add your tasks to it.

**Comment by lsh-0** [comment]
How we going with this?

**Comment by nlisgo** [comment]
Here is the epic: https://github.com/elifesciences/issues/issues/8311

Feel free to add tickets to it.

I propose that we change the property to `sentForReview` rather than `sentForPeerReview` to match the value in the XML.

**Comment by nlisgo** [comment]
Updated to `sentForReview`.

**Comment by nlisgo** [comment]
Expectation is that the date should be in the format: `YYYY-MM-DD`.

**Comment by lsh-0** [comment]
Still fine, good to go.

**Comment by nlisgo** [comment]
Added CHANELOG entry. Once it is green I will hit the merge button and add the tag once the `dist/` folder has been regenerated.

**Pull request merged**
