### PR TITLE
/article deprecations and obsolesence

### PR DESCRIPTION
**Pull request by lsh-0**
* removes poa v1 and vor v1. 
* deprecates vor v2

### CODE REVIEW

**Comment by lsh-0** [comment]
poa v1 and vor v1 were deprecated years ago so I've finally removed them. Lax was doing a lot of gymnastics to downgrade and upgrade content that just isn't tenable anymore.

When support for structured abstracts is done I'll open another PR to:
* drop the 'experimental' against poa v3
* add a 'deprecated' against poa v2
* remove vor v2
* add a 'deprecated' against vor v3
* remove 'experimental' against vor v4

**Comment by lsh-0** [comment]
(should I include anyone else as a reviewer?)

**Review by nlisgo — APPROVED** [review]
Happy to move on this. Think we should meet soon to discuss making more mime types deprecated and scheduling their removal.

**Comment by lsh-0** [comment]
- [x] blocked by [lax](https://github.com/elifesciences/lax/pull/534)

**Comment by lsh-0** [comment]
changes to lax for structured abstracts and the dropping of support for v1 poa and vor spec has been successfully deployed, merging this .

**Pull request merged**
